package interfaces;

import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {

    Connection cnx;
    
    public Principal() {
        initComponents();
        cnx = clases.Conexion.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuConfiguracion = new javax.swing.JMenu();
        itemCertificaciones = new javax.swing.JMenuItem();
        itemLocalidades = new javax.swing.JMenuItem();
        itemModulos = new javax.swing.JMenuItem();
        itemProvincias = new javax.swing.JMenuItem();
        itemSedes = new javax.swing.JMenuItem();
        itemTipos = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton1);
        jButton1.setBounds(50, 40, 72, 29);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuConfiguracion.setMnemonic('e');
        menuConfiguracion.setText("Configuracion");

        itemCertificaciones.setMnemonic('t');
        itemCertificaciones.setText("Certificaciones");
        itemCertificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCertificacionesActionPerformed(evt);
            }
        });
        menuConfiguracion.add(itemCertificaciones);

        itemLocalidades.setMnemonic('y');
        itemLocalidades.setText("Localidades");
        itemLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLocalidadesActionPerformed(evt);
            }
        });
        menuConfiguracion.add(itemLocalidades);

        itemModulos.setMnemonic('p');
        itemModulos.setText("Módulos");
        itemModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModulosActionPerformed(evt);
            }
        });
        menuConfiguracion.add(itemModulos);

        itemProvincias.setMnemonic('d');
        itemProvincias.setText("Provincias");
        itemProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProvinciasActionPerformed(evt);
            }
        });
        menuConfiguracion.add(itemProvincias);

        itemSedes.setText("Sedes");
        menuConfiguracion.add(itemSedes);

        itemTipos.setText("Tipos de Documentos");
        itemTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTiposActionPerformed(evt);
            }
        });
        menuConfiguracion.add(itemTipos);

        menuBar.add(menuConfiguracion);

        menuSalir.setMnemonic('h');
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuSalir.add(itemSalir);

        menuBar.add(menuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void itemLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLocalidadesActionPerformed
        Localidad ventanaLocalidades = new Localidad(cnx);
        if(cnx != null)
        {   
            desktopPane.add(ventanaLocalidades);
            ventanaLocalidades.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sin Conexion!!...");
    }//GEN-LAST:event_itemLocalidadesActionPerformed

    private void itemProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProvinciasActionPerformed
        Provincia ventanaProvincias = new Provincia(cnx);
        if(cnx != null)
        {   
            desktopPane.add(ventanaProvincias);
            ventanaProvincias.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sin Conexion!!...");
    }//GEN-LAST:event_itemProvinciasActionPerformed

    private void itemCertificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCertificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCertificacionesActionPerformed

    private void itemModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModulosActionPerformed

    }//GEN-LAST:event_itemModulosActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed

    }//GEN-LAST:event_menuSalirActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        try {
            cnx.close();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTiposActionPerformed
        TipoDocumento ventanaTipo = new TipoDocumento(cnx);
        if(cnx != null)
        {   
            desktopPane.add(ventanaTipo);
            ventanaTipo.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sin Conexion!!...");
    }//GEN-LAST:event_itemTiposActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //clases.Persona.insertar(cnx, 1, "23811", "zamar", "javier", Date.valueOf("1974-02-23"), "1543", "gmail", "100 viv", 1);
        //clases.Persona.insertar(cnx, 1, "23588", "coto", "guadalupe", Date.valueOf("1973-12-08"), "1553", "hotmail", "25 de mayo", 2);
        clases.Persona.modificar(cnx, 1, "40828", "zamar coto", "tomas", Date.valueOf("2004-01-19"), "1543", "gmail", "bolivia 1960", 1,3);
       //clases.Persona.restaurar(cnx, 2);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem itemCertificaciones;
    private javax.swing.JMenuItem itemLocalidades;
    private javax.swing.JMenuItem itemModulos;
    private javax.swing.JMenuItem itemProvincias;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemSedes;
    private javax.swing.JMenuItem itemTipos;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConfiguracion;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
